export const FETCH_RECIPE = 'FETCH_RECIPE';
export const SOMETHING_FAILED = 'SOMETHING_FAILED';
// export const INVALIDATE_RECIPE = 'INVALIDATE_RECIPE';
export const REQUEST_RECIPES = 'REQUEST_RECIPES';
export const RECEIVE_STEPS = 'RECEIVE_STEPS'
export const RECEIVE_RECIPES = 'RECEIVE_RECIPES';
export const RECEIVE_INGREDIENTS = 'RECEIVE_INGREDIENTS';
export const HAS_ERRORED = 'HAS_ERRORED';
